### ISSUE TITLE
Setup wizard no detect ethernet network connected

### ISSUE THREAD

**Issue by tuccy** [opengapps/aosp_build#10]
hi all after build with prebuilts gapps setupwizard no detect ethernet conection is properly configured in my framework overlay but always apear wifi configuratión step i think that is application problem.

**Comment by mfonville** [comment]
Hmm, I think in that case the Google Setup Wizard is not equipped to deal with this situation and always assumes that a Wi-Fi connection must be available.
Maybe you could manually delete Google's Setup Wizard after installation (e.g. using the recovery filemanager or command line)?

**Comment by Blystad** [comment]
I don't think there's much we can do regarding the setup wizard (Seeing as we don't have its source code).

Do you have a scenario where it works as you expect? e.g. by downloading a opengapps recovery update.zip and flashing that.

**Comment by Blystad** [comment]
Closing this since it hasn't been updated for a while (and we can't really control what happens in the SetupWizard).
