### ISSUE TITLE
Localization is not working in nougat devices

### ISSUE THREAD

**Issue by Muthukathiravan** [opengapps/aosp_build#102]
Locale locale = new Locale("es");
        Locale.setDefault(locale);
        Configuration config = new Configuration();
        config.locale = locale;
        getBaseContext().getResources().updateConfiguration(config,
                getBaseContext().getResources().getDisplayMetrics());

        Resources.getSystem().updateConfiguration(config, null);

**Comment by Blystad** [comment]
How is this an OpenGapps problem?

**Comment by Blystad** [comment]
Closing issue due to no response in 10 days.
