### ISSUE TITLE
copying to system/vendor not allowed when building separate vendor partition

### ISSUE THREAD

**Issue by jamuir** [opengapps/aosp_build#106]
We hit the following error when building a Marshmallow image for bullhead:

```
Non-symlink out/target/product/bullhead/system/vendor detected!
You cannot install files to out/target/product/bullhead/system/vendor while building a separate vendor.img!
build/core/Makefile:1030: recipe for target 'out/target/product/bullhead/obj/PACKAGING/systemimage_intermediates/system.img' failed
make: *** [out/target/product/bullhead/obj/PACKAGING/systemimage_intermediates/system.img] Error 1
```

It is caused by the `PRODUCT_COPY_FILES` statements generated for "pittpatt" in `vendor/google/build/opengapps-files.mk`:

```
# Pico and higher
ifneq ($(filter $(TARGET_GAPPS_VARIANT),pico),)
# vendor/pittpatt seems to be removed on N+ (so only copy it to older than N)
ifeq ($(filter $(call get-allowed-api-levels),24),)
  PRODUCT_COPY_FILES += $(call gapps-copy-to-system,all,vendor/pittpatt)
endif
  PRODUCT_COPY_FILES += $(call gapps-copy-to-system,all,usr/srec)
endif
```

Since we build a vendor image in our build, the pittpatt files should be copied to "/vendor" rather than "/system/vendor".

**Comment by jamuir** [comment]
We have fixed this locally by skipping the pittpatt copy statements when the device is bullhead (those files actually get copied to the vendor image by a statement in a separate part of our in-house build).

But rather than using device-type check, what we should really be doing is checking whether a vendor image is being built (and altering generating different `PRODUCT_COPY_FILE` statements).

Inside the "build" project, the statement "ifdef BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE" is used to do that, but that doesn't work inside `vendor/google/build/opengapps-files.mk` because of the way the opengapps makefiles are included in the build system; they are processed before `device/lge/bullhead/BoardConfig.mk`.

**Comment by Blystad** [comment]
I tried fixing this with https://github.com/opengapps/aosp_build/pull/65 but that didn't work, because of how stuff is processed.

See original issue https://github.com/opengapps/aosp_build/issues/63

The project I build doesn't have a vendor/ partition, so it's a bit difficult for me to test. I would welcome PRs that fixes this issue, since this seems to be a recurring issue.

You could try `get_build_var` and `get_abs_build_var` (from `source/buildenv.sh`), maybe that'll get the value necessary.

**Comment by mfonville** [comment]
A short addendum: in Nougat the libfrsdk.so seems to have moved from `/vendor` to the directory of the facelock apk itself, and pittpatt has been removed;
I still have to incorporate those changes, but it seems that over time this issue will resolve itself and system related stuff will not be put on that partition anymore.

**Comment by jamuir** [comment]
@Blystad , @mfonville :  thanks for your comments and the pointer to #63.

I will open a PR in the next few days to address this.

As I mentioned before (in a different thread), rather than using the file `vendor/google/build/config.mk`, I'd like to try incorporating opengapps into the build in a different way.  This should alleviate the problems we see with build variables not being defined.  If I can't get that to work, then I will resort to calling `get_build_var` / `get_abs_build_var` as suggested above :-)

**Comment by Fuzion24** [comment]
@jamuir any updates here?

**Comment by jamuir** [comment]
no, no progress from me yet.

I will try to find some time next week to look at this.

**Comment by jamuir** [comment]
@Fuzion24:  I have a branch that should resolve this, but I haven't tested it yet.  You are welcome to give it a try:

https://github.com/GraphiteSoftware/aosp_build/tree/jm-system-vendor

**Comment by jamuir** [comment]
fix has been merged.

closing.
