### ISSUE TITLE
Setup BackupTransport overlay

### ISSUE THREAD

**Issue by Blystad** [opengapps/aosp_build#109]
See: https://android.googlesource.com/device/sample/+/4b3880d/overlays/backup/frameworks/base/packages/SettingsProvider/res/values/defaults.xml

We need to add that to make the Google Backup system work.

**Comment by mfonville** [comment]
Should these also added by regular ROMs that want GApps compatiblity?

**Comment by Blystad** [comment]
Yes. The default backup transport is meant for local testing.

**Comment by Blystad** [comment]
Should we consider creating a repo with all overlays that is necessary? I've probably received 400 emails with people cherry-picking in the webview commit. Would be easier if we just told them

"Add this repo, and add this line to the end of your `device.mk` and you're good to go!"

**Comment by mfonville** [comment]
@thecrazylex what is your opinion on an overlay repo?

**Comment by TheCrazyLex** [comment]
I think the Version specific problems are not always related to overlays. Some may require in-code changes. So such a seperate repo wouldn't be a full solution.

**Comment by Blystad** [comment]
Some things would be constant. E.g. the webview patch, the location provider and the backup provider.

If the location provider is configured correctly, then the marshmallow permission code patch is totally unnecessary (as is evident that it's not present if you decompile the framework.jar from an official system image).

But, I guess some patches are needed if you want to support Google Play opt-in. Instead of building it as part of the system image (as I do).
