### ISSUE TITLE
GAPPS_EXCLUDED_PACKAGES doesn't work

### ISSUE THREAD

**Issue by Kruncho** [opengapps/aosp_build#119]
I'm trying to build a custom device with only `PrebuiltGmsCore` and `GoogleServicesFramework` Gapps and my `device.mk` looks a bit like this : 
```
GAPPS_VARIANT := pico

GAPPS_EXCLUDED_PACKAGES := \
    GoogleBackupTransport \
    GooglePartnerSetup \
    GoogleOneTimeInitializer \
    GoogleContactsSyncAdapter \
    GoogleFeedback \
    GoogleContactsSyncAdapter \
    GoogleLoginService \
    SetupWizard \
    Phonesky \
    GoogleCalendarSyncAdapter \
    GoogleTTS \
    GooglePackageInstaller

$(call inherit-product, vendor/google/build/opengapps-packages.mk)
```

But when I build the device, I saw that the supposed excluded packages where embeded in the final image.

I tried to debug it and I saw that the variable `PRODUCT_PACKAGES` contains exactly what I need so I don't know why I have all theses extra packages.

**Comment by jamuir** [comment]
@Kruncho:  Try rebuilding your image after doing "make installclean".  If the packages that were supposed to be excluded are still there, then there is probably an issue with the makefiles.

At the company I work for, we use `GAPPS_EXCLUDED_PACKAGES` in our nightly builds and it seems to work correctly.  We use the stock variant, but exclude apps like PlusOne, Hangouts and PlayGames.

**Comment by jamuir** [comment]
any more information?  if not, then I say this issue can be closed.

**Comment by Kruncho** [comment]
Sorry for the late answer. I wasn't able to test the generated image into our device (it's a custom one) but I saw in `/system/priv-apps` that the only applications that I wanted were there. So I guess you can close the issue. Thank you for the support :)

**Comment by jamuir** [comment]
np :-)

**Comment by jamuir** [comment]
@Blystad : could you close this issue please?
