### ISSUE TITLE
Need to patch DefaultPermissionGrantPolicy.java for GApps on 6.0

### ISSUE THREAD

**Issue by jcppkkk** [opengapps/aosp_build#12]
If we build gapps in aosp 6.0 source tree, a patch should be applied as  [Notes-for-Android-6.0](https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0) saying

```
cd frameworks/base
curl https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a.patch | patch -p1
```

**Comment by Blystad** [comment]
People probably won't read a notice...we can add a compile check to see if the file contains some content we expect.

But...there must be a better way of doing this...I doubt Google uses that patch...usually they just add stuff to an XML file and that fixes everything.

**Comment by mfonville** [comment]
Google benefits that they sign their ROM with the same key as they sign their apps, which automatically grants the permissions to their GApps. (at leas that is how I understand it)

**Comment by Blystad** [comment]
Hmm, what about Samsung, Sony etc?

**Comment by mfonville** [comment]
We have no clue. We expect that they set these permissions explicit in their source, but we should indeed investigate your comment https://github.com/opengapps/opengapps/issues/93#issuecomment-171780047

**Comment by mikalackis** [comment]
I have a problem with building AOSP 6.0 for Nexus 5 and including opengapps. I created a post on xda too: http://forum.xda-developers.com/showpost.php?p=65355535&postcount=1993

Is everyone having the same issue with pure AOSP builds? From what I understood, on AOSP including the patch from first comment should do the trick and I did it but I still have issues.

**Comment by Blystad** [comment]
Have you assigned Google mobile services as a network location provider?

See https://github.com/CyanogenMod/android_vendor_cm/blob/cm-12.1/overlay/common/frameworks/base/core/res/res/values/config.xml

**Comment by mikalackis** [comment]
That completely did the trick :) Thanks for helping me

**Comment by Blystad** [comment]
Great. I guess we should add that to our overlays since it's always needed.

**Comment by fonic** [comment]
The patch linked by jcppkkk is outdated. Until this is added to OpenGApps, here are two patches that work flawlessly with the current Android AOSP 6.0 master branch.

[opengapps_default_permissions.patch.txt](https://github.com/opengapps/aosp_build/files/181892/opengapps_default_permissions.patch.txt)
[opengapps_location_provider.patch.txt](https://github.com/opengapps/aosp_build/files/181893/opengapps_location_provider.patch.txt)

**Comment by Dudulle** [comment]
Do you really need the first patch?
I have no issue without this on Marshmallow.

Adding the location provider to the overlay should be enough for Android to accept Google's signature and apply those permissions automatically.

**Comment by Blystad** [comment]
Adding gms as location provider should be the only thing necessary.

**Comment by fonic** [comment]
Thanks for the hint! I haven't tested it yet without the first patch.

**Comment by bomin-kim** [comment]
Editing config.mk file is enough for working Google Play Services, but if you want to grant other permissions to packages. Use [Notes for Android 6.0](https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0) patch with minor modifications.

`PackageParser.Package getDefaultProviderAuthorityPackageLPr(String authority, int userId)` will always return `null`. So `grantRuntimePermissionsLPw(PackageParser.Package pkg, Set<String> permissions, int userId)` is not executed.

Instead of using `PackageParser.Package getDefaultProviderAuthorityPackageLPr(String authority, int userId)`  function, use  `PackageParser.Package getPackageLPr(String packageName)` function. It will return PackageParser.Package object properly. So granting permissions will be executed.

**Comment by mfonville** [comment]
Otherwise, this is also a workaround :)
https://github.com/opengapps/all/commit/de7dc7e1b977c7ebc250699764d2e9aa165e70ca

**Comment by Drjacky** [comment]
@Blystad @bomin-kim @fonic I want to add `android.permission.INTERACT_ACROSS_USERS` permission to `com.google.android.gms` package. I'm working on Android 4.4.4, and there is no `DefaultPermissionGrantPolicy`; So patches doesn't work for me. How to edit config.xml file to add such a this permission?

**Comment by Blystad** [comment]
Why do you want to add the permission? What error do you see?

All Google Apps runs as a shared user id, so INTERACT_ACROSS_USERS shouldn't be necessary.
