### ISSUE TITLE
Add option to enable Google Assistant during AOSP build?

### ISSUE THREAD

**Issue by amitash** [opengapps/aosp_build#122]
I have been trying to get Google Assistant from OpenGapps during AOSP build and there seems to be no options. Is this implemented in the aosp_build system for OpenGApps?

**Comment by mfonville** [comment]
@Blystad it would require adding a trivial value to build.prop to enable this

**Comment by jamuir** [comment]
for reference, see https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L2276 .

we could add the following to `opengapps-packages.mk`:

```makefile
PRODUCT_PROPERTY_OVERRIDES += \
    ro.opa.eligible_device=true
```

**Comment by alviteri** [comment]
@jamuir @mfonville ro.opa.eligible_device=true works tested for a while on all sony aosp devices
