### ISSUE TITLE
How to exclude multiple packages?

### ISSUE THREAD

**Issue by vasilmkd** [opengapps/aosp_build#133]
Hello, I successfully built a nexus 6 aosp rom with the stock package. However, I am unable to complete a dist build (I am experimenting with signing the rom), it says that system.img runs out of space. I am new to makefiles and would like to know how to exclude multiple packages from the build, in order to free up more space in /system.

Thanks in advance.

**Comment by vasilmkd** [comment]
Also, the dist build is always failing at the end with
"Could not append verity data: error: file write: incomplete write".
Any help would be greatly appreciated.

**Comment by jamuir** [comment]
In the readme file https://github.com/opengapps/aosp_build/blob/master/README.md , it says you can use the variable `GAPPS_EXCLUDED_PACKAGES` to do this; e.g.
```makefile
GAPPS_EXCLUDED_PACKAGES := \
    PlusOne \
    Hangouts
```
The verity error is likely because you are running out of space on the system image.  Try to get your `dist` build working without any Google apps first (or maybe use the `pico` or `nano` package).  Once that works, then you can try adding (more) Google apps.

**Comment by jamuir** [comment]
Note that we build Nexus 6 roms in-house with OpenGapps integrated in them.

**Comment by vasilmkd** [comment]
Any tips then on how to get a fully signed build (which OpenGapps package)? Right now I am running a test-keys build of android-7.1.2_r8 with the stock OpenGapps package and the android-7.1.1_r40 kernel (which I believe is the newest for the Nexus 6). I am generally happy with it, but I am really paranoid when it comes to security and would like to run a signed build just to get a usable recovery image, which cannot just be flashed without unlocking the bootloader.

Thanks in advance!

P.S. I tried an unsuccessful dist build with the variable set like the following:

GAPPS_EXCLUDED_PACKAGES += \
    PlusOne \
    Hangouts.

Note the +=, not :=. Is that wrong? As I said, I am very new to all this.

**Comment by jamuir** [comment]
No tips other than what I suggested already (i.e. get your "dist" build working without opengapps first, and then try adding them).

If you look at the makefile `opengapps-packages.mk`, then you will see how `GAPPS_EXCLUDED_PACKAGES` is used.

Note that the manual for gnu-make is a very good reference.  The commands `$(error ...)` and `$(warning ...)` are useful for debugging makefiles.

**Comment by vasilmkd** [comment]
Just an update. I tracked down the source of the verity error. I had to resize my /tmp partition from 4Gb to 8Gb. During the signing, the build process uses around 5Gb of the /tmp, at least on my machine.
