### ISSUE TITLE
GAPPS_EXCLUDED_PACKAGES Not Working

### ISSUE THREAD

**Issue by admiralspeedy** [opengapps/aosp_build#135]
GAPPS_EXCLUDED_PACKAGES definitely does not work. I'm trying to build my own custom version of Lineage with the Stock package of Open GApps for my Pixel XL, but I want to exclude a bunch of apps and using GAPPS_EXCLUDED_PACKAGES does nothing. All of the apps that I list are included when I build.

I read the previous report on this and "make cleaninstall" didn't change anything and the first time I built with GApps I did a totally clean build anyways (with "make clobber" before building).

**Comment by admiralspeedy** [comment]
I think I figured it out. The packages names are not the same as those listed on the Wiki. I had to go into the makefile and find the names myself... Kind of stupid.

**Comment by jamuir** [comment]
also, don't forget to use line-continuation characters when doing a multi-line assignment to `GAPPS_EXCLUDED_PACKAGES`.
