### ISSUE TITLE
`lunzip` isn't packaged for some distros, please use `lzip -d` instead

### ISSUE THREAD

**Issue by ackalker** [opengapps/aosp_build#141]
Trying to integrate Open GApps into Android-x86, I'm getting the following error when I try to build:
```
vendor/google/build/config.mk:31: *** lunzip is not available. Please install it first ("sudo apt-get install lunzip").  Stop.
```

Some distros, including Void Linux which I use, do not package `lunzip` but do package `lzip`, I presume because `lzip` already has a `-d` option to decompress `.lz` files.
Please consider using `lzip -d` instead of `lunzip`.

**Comment by Blystad** [comment]
Ubuntu is the official recommended Linux distro for Androids builds. On other Linux distros YMMV. But, PR welcome :)

**Comment by mfonville** [comment]
Also on Ubuntu `lzip -d` is available if lzip itself installed, while `lunzip` is only available if itself is installed. Maybe use an OR-statement to try either of the two?

**Comment by deeproot2k** [comment]
I got past this by just installing the tgz from http://download.savannah.gnu.org/releases/lzip/lunzip/
after the make install it was where it was needed.

**Comment by jamuir** [comment]
@ackalker :  would you consider opening a PR to fix this?

**Comment by jamuir** [comment]
see PR #180

**Comment by jamuir** [comment]
PR is merged.  closing.
