### ISSUE TITLE
Excluding Packages not working

### ISSUE THREAD

**Issue by cydia2020** [opengapps/aosp_build#142]
Hey, excluding packages doesn't seems to work, even if I enter the excluding packages "command", it's still not working, the excluded packages are still copying into the ROM. Any ideas? Cheers.

[Here's the device.mk](https://github.com/cydia2020/android_device_google_marlin/blob/n-mr2/device-common.mk)

**Comment by jamuir** [comment]
You need line continuation characters, like this:

```make
GAPPS_EXCLUDED_PACKAGES := \
  PackageInstallerGoogle \
  GoogleNow \
  NewsWidget \
  Newsstand \
# etc...
```
Also, I'm not sure if all of your package-names are correct (e.g. "Movies" seems suspicious).

**Comment by cydia2020** [comment]
Yes, if you see the change history, you’ll find that I tried this before

Cheers

Windows 10 版のメ`ル<https://go.microsoft.com/fwlink/?LinkId=550986>から送信

差出人: James Muir<mailto:notifications@github.com>
送信日r: 2017年7月28日 10:14
宛先: opengapps/aosp_build<mailto:aosp_build@noreply.github.com>
CC: 池程 (Takumi Ikezaki)<mailto:cydia2020@live.cn>; Author<mailto:author@noreply.github.com>
件名: Re: [opengapps/aosp_build] Excluding Packages not working (#142)


You need line continuation characters, like this:

GAPPS_EXCLUDED_PACKAGES := \

  PackageInstallerGoogle \

  GoogleNow \

  NewsWidget \

  Newsstand \

# etc...

Also, I'm not sure if all of your package-names are correct (e.g. "Movies" seems suspicious).

―

**Comment by cydia2020** [comment]
And the package names are from https://github.com/opengapps/opengapps/wiki/Package-Comparison

**Comment by jamuir** [comment]
Don't go by that wiki.  The package names need to match module names inside `vendor/google/build/modules`.  Grep for `LOCAL_MODULE` inside that directory.

**Comment by jamuir** [comment]
Also, take a look at `vendor/google/build/opengapps-packages.mk` to see how the variable `GAPPS_EXCLUDED_PACKAGES` is used (you will also see package names in that file).

**Comment by jamuir** [comment]
@cydia2020 :  can this be closed?

**Comment by cydia2020** [comment]
Package installer seems is still there although others have been removed

Regards
Cheng Chi
Cheers

????　???　??
??????????????

________________________________
