### ISSUE TITLE
Binaries version maintaining in git

### ISSUE THREAD

**Issue by kyvaith** [opengapps/aosp_build#144]
How often binaries in git are updated? Is there any crawler with pull newest available versions? I see lot of outdated binaries. Should I make pull request to get newer ones in Yours repository?

**Comment by Blystad** [comment]
What binaries? are you talking about the binaries in `opengapps/arm` and `opengapps/all`?

**Comment by mfonville** [comment]
@NicholasBuse can tell you more :-)

**Comment by NicholasBuse** [comment]
I update any APKs that our crawlers find multiple times a day to our 5 APK repos:
- [all](https://github.com/opengapps/all)
- [arm](https://github.com/opengapps/arm)
- [arm64](https://github.com/opengapps/arm64)
- [x86](https://github.com/opengapps/x86)
- [x86_64](https://github.com/opengapps/x86_64)

![NicholasBuse commits over last year](https://cdn.pbrd.co/images/GNwXE4o.png)
