### ISSUE TITLE
"Setup Wizard has stopped" on Nexus5X AOSP when selecting WiFi network

### ISSUE THREAD

**Issue by NateDev100** [opengapps/aosp_build#155]
I've just compiled a fresh AOSP build with OpenGapps AOSP_Build and when I choose the WiFi network that I want to connect to in the setup wizard, it crashes.

Steps to reproduce: Build fresh AOSP images for the Nexus 5X and include opengapps aosp_build. Select the WiFi network on the "Get Connected" page and the setup wizard will crash, even if you repeat it, leaving you unable to connect to WiFi in the setup wizard.

**Comment by alviteri** [comment]
I personally tested all sony ( xperia x compact xperia x performance xperia xz1 xperia x premium ) all of them builded oreo and no crashes ... can you please post a log?

**Comment by NateDev100** [comment]
How do I get a log?

**Comment by NateDev100** [comment]
Nevermind, I will close this, for some reason the packages/apps/Setting directory got deleted, that's why it was crashing. Sorry, my bad :)
