### ISSUE TITLE
I've downloaded on http://opengapps.org.

### ISSUE THREAD

**Issue by TianLuhua** [opengapps/aosp_build#159]
I've downloaded on http://opengapps.org.

Platform:ARM
Android:7.1
Variant:pico

OpenGApps AOSP based build system. 
what should i do?
help me!

**Comment by alviteri** [comment]
This is not an issue if you have download gapps.zip then you need a proper recovery to install it

**Comment by TianLuhua** [comment]
Can you read Chinese?
Because I come from China.

**Comment by TianLuhua** [comment]
I have downloaded Opengapps
There are now AOSP compiler environment, can compile the built-in Open GApps?
