### ISSUE TITLE
libfacenet.so in arm 26 arch is incorrect

### ISSUE THREAD

**Issue by SquallATF** [opengapps/aosp_build#163]
`file vendor/opengapps/sources/arm/lib/26/libfacenet.so
vendor/opengapps/sources/arm/lib/26/libfacenet.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[md5/uuid]=903b91e69fbf371a5f6fe141c3739256, stripped
`

**Comment by jamuir** [comment]
@mfonville :  was `libfacenet.so` committed to the wrong project?

**Comment by jamuir** [comment]
@NicholasBuse :  any thoughts on the issue above?  It seems like `libfacenet.so` was pushed to the wrong project.

https://github.com/opengapps/arm/tree/master/lib/26

**Comment by jamuir** [comment]
@Blystad : do you know of a good way to bring this issue to the attention of the contributors to https://github.com/opengapps/arm ?

maybe this issue should be moved to https://github.com/opengapps/opengapps .

**Comment by jamuir** [comment]
@SquallATF :  there is a PR for this issue here:

https://github.com/opengapps/arm/pull/4
