### ISSUE TITLE
Pixel 2 (Walleye) SetupWizard

### ISSUE THREAD

**Issue by TresReinosDeLeche** [opengapps/aosp_build#167]
SetupWizard Cannot restore from cloud, FC's.

Must start new account to continue.

**Comment by jamuir** [comment]
What does "FC" stand for?

Please post logcat output.

**Comment by jamuir** [comment]
re-reading this now, my guess is that "FC" is "force close".

**Comment by alviteri** [comment]
SetupWizard worked for me on all Sony devices and also on taimen device.... Can we close this @jamuir ?

**Comment by jamuir** [comment]
Thanks for checking SetupWizard on your devices.

Without logs or steps-to-reproduce, there is not much we can do.

closing.
