### ISSUE TITLE
Problem with GoogleCamera force closing

### ISSUE THREAD

**Issue by nicedream06** [opengapps/aosp_build#171]
I'm building AOSP 8.1 w/ OpenGapps for Google Pixel 1st gen, and getting force close errors from Google Camera. 

It looks like there was a workaround for this problem in the opengapps repository, in this changeset:
https://github.com/opengapps/opengapps/pull/594/commits/d5edc9e515ee8357950845fb4c0cb92ac3e53596 

Is there any way to force a specific version of the Camera app when using the aosp_build repository?

**Comment by alviteri** [comment]
I think you have open source cam Hal if yes then you should add these commits to avoid FC
https://github.com/sonyxperiadev/camera/commit/d131e6d74af326f68cc5187a94af60ccbd0651b4
https://github.com/sonyxperiadev/camera/commit/09a6e79b6fcf39e1dcd9d9c5802b40a057b57391

**Comment by nicedream06** [comment]
These commits would not apply against the same files in AOSP.  But I went through each of them with a diff tool, and it appears that the code added in those commits is already in AOSP.  So I believe something else is causing the crash with the current version of Google Camera in 8.1.

I'm going to continue digging...
