### ISSUE TITLE
PackageManager refuses to install Chrome [SDK 27] [8.1.0_r20]

### ISSUE THREAD

**Issue by argraur** [opengapps/aosp_build#174]
When using any Chrome package it does not install with following PackageManager message:
Do you have any ideas?

```04-08 17:27:23.214   828   828 I PackageManager: /system/app/Chrome changed; collecting certs
04-08 17:27:23.690   828   828 W PackageManager: Failed to scan /system/app/Chrome: Failed to collect certificates from /system/app/Chrome/Chrome.apk using APK Signature Scheme v2

**Comment by alviteri** [comment]
Which Android version ?

**Comment by argraur** [comment]
android-8.1.0_r20 (OPM2.171019.029) April security patch

**Comment by alviteri** [comment]
Same Android version on a Sony device and installed chrome without any conflicts .... Can I close ?

**Comment by argraur** [comment]
Happens only on April security patch if wiping system partition using make_ext4fs (that TWRP uses)
For fix needs ROM to be flashed 2 times
Seems like I/O error
