### ISSUE TITLE
Build fail los 15.1

### ISSUE THREAD

**Issue by bretantonio** [opengapps/aosp_build#176]
I included aospbuild and arm repos
error
[1058/1130] including ./vendor/opengapps/build/modules/Books/Android.mk ...
vendor/opengapps/build/core/prebuilt_apk.mk:50: error: Unable to find APK for Books.

**Comment by alviteri** [comment]
First of all which variant of gapps did you use ?

**Comment by bretantonio** [comment]
stock

**Comment by Blystad** [comment]
Have you remembered to include the `all` repo?

https://github.com/opengapps/all/tree/master/app/com.google.android.apps.books/16/nodpi

**Comment by bretantonio** [comment]
include them where?

**Comment by alviteri** [comment]
Yep that was the problem @Blystad probably he forgot to include it

**Comment by Blystad** [comment]
See step 1 in Getting started at https://github.com/opengapps/aosp_build

**Comment by bretantonio** [comment]
@Blystad I had just repo synced arm and aospbuild folders only let me clone all folder and see what happens

**Comment by alviteri** [comment]
Include this in manifest.xml

<remote name="opengapps" fetch="https://github.com/opengapps/"  />

<project path="vendor/opengapps/build" name="aosp_build" revision="master" remote="opengapps" />
<project path="vendor/opengapps/sources/all" name="all" clone-depth="1" revision="master" remote="opengapps" />


<project path="vendor/opengapps/sources/arm" name="arm" clone-depth="1" revision="master" remote="opengapps" />
<project path="vendor/opengapps/sources/arm64" name="arm64" clone-depth="1" revision="master" remote="opengapps" />

**Comment by bretantonio** [comment]
Turns out i had to sync the [all](https://github.com/opengapps/all) repo. Now its fine thanks
