### ISSUE TITLE
Unable to Compile LineageOS 14.1 for Nexus 6P

### ISSUE THREAD

**Issue by Swift-Studio** [opengapps/aosp_build#179]
Full error messages:
`find: `/home/longhorn3683/swiftos/out/target/common/obj/SHARED_LIBRARIES/libwifi-hal-mock_intermediates': 没有那个文件或目录
build/core/base_rules.mk:183: *** .: MODULE.TARGET.APPS.GCS already defined by vendor/huawei/angler.
build/core/ninja.mk:166: recipe for target '/home/longhorn3683/swiftos/out/build-lineage_angler.ninja' failed
make: *** [/home/longhorn3683/swiftos/out/build-lineage_angler.ninja] Error 1
make: Leaving directory '/home/longhorn3683/swiftos'

#### make failed to build some targets (01:06 (mm:ss)) ####
`
device/huawei/angler/device.mk:
`GAPPS_VARIANT := nano
$(call inherit-product, vendor/opengapps/build/opengapps-packages.mk)
GAPPS_FORCE_PACKAGE_OVERRIDES := true
PRODUCT_PACKAGES += Chrome
PRODUCT_PACKAGES += GoogleCamera
PRODUCT_PACKAGES += GoogleHome
`

**Comment by argraur** [comment]
Remove GCS entry from vendor/huawei/angler/Android.mk if you want to use OpenGApps GCS or remove vendor/opengapps/build/modules/GCS if you want to use one from Huawei proprietary blobs

**Comment by Swift-Studio** [comment]
@argraur Remove GCS and Tycho can be compiled. Thanks!

**Comment by Swift-Studio** [comment]
@argraur Removing GCS and Tycho can started compiling, but the result is not yet known.

**Comment by argraur** [comment]
Nah they are Google apps anyway, result cant be bad

**Comment by argraur** [comment]
@alviteri I think you can close this.
