### ISSUE TITLE
Black screen in google signin prompt (LineageOS 15.1 build)

### ISSUE THREAD

**Issue by sreehax** [opengapps/aosp_build#183]
I tried to build LineageOS 15.1 with gapps bundled in so that I can do delta updates (system partition must not be modified) with my own update server. The rom is built correctly, and the phone boots into the google setup wizard. I can connect to wifi/data and when i need to sign into a google account, the google sign in prompt is not loaded, and there is a black screen. I can reboot or power off, and the navbar and statusbar are still visible. Rebooting does not fix the issue.

**Comment by Blystad** [comment]
Any useful information in logcat?

**Comment by sreehax** [comment]
@Blystad I can't get a logcat since USB Debugging cannot be enabled yet.

**Comment by alviteri** [comment]
Check pstore

**Comment by sreehax** [comment]
@alviteri It's probably too late for this, for now I gave up and installed the open gapps stock zip (modified the system partition). I can check later by flashing my broken build again.

**Comment by alviteri** [comment]
It should be the best since without log we can't help ...

**Comment by sreehax** [comment]
@alviteri yeah I will post a logcat later

**Comment by Blystad** [comment]
If you build a userdebug build then ADB is enabled by default. At least in
normal AOSP.

**Comment by sreehax** [comment]
actually this was because permissions weren't set or something like that. I ended up building an qemu-arm chroot to run update-binary and install the gapps to $OUT/system, then rebuild target-files, then sign target-files. Works fine for me

**Comment by jamuir** [comment]
Too bad there weren't any logs provided here.  I am seeing something similar in a new oreo (8.1) build.

It is happening because a webview implementation cannot be located.  I am using a pre-built vendor image and it is possible that may be breaking webview somehow.

```
10-09 19:49:31.302 I/SystemServer( 1394): u0 : WebViewFactoryPreparation
10-09 19:49:31.303 E/WebViewUpdater( 1394): u0 : error preparing webview provider from system server
10-09 19:49:31.303 E/WebViewUpdater( 1394): com.android.server.webkit.WebViewUpdater$WebViewPackageMissingException: Could not find a loadable WebView package
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.webkit.WebViewUpdater.findPreferredWebViewPackage(WebViewUpdater.java:320)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.webkit.WebViewUpdater.prepareWebViewInSystemServer(WebViewUpdater.java:142)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.webkit.WebViewUpdateServiceImpl.prepareWebViewInSystemServer(WebViewUpdateServiceImpl.java:95)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.webkit.WebViewUpdateService.prepareWebViewInSystemServer(WebViewUpdateService.java:127)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.SystemServer.lambda$-com_android_server_SystemServer_77314(SystemServer.java:1716)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.-$Lambda$T7cKu_OKm_Fk2kBNthmo_uUJTSo$2.$m$0(Unknown Source:4)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.-$Lambda$T7cKu_OKm_Fk2kBNthmo_uUJTSo$2.run(Unknown Source:0)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.SystemServerInitThreadPool.lambda$-com_android_server_SystemServerInitThreadPool_2249(SystemServerInitThreadPool.java:64)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.-$Lambda$Ganck_s9Kl5o2K6eVDoQTKLc-6g.$m$2(Unknown Source:8)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.server.-$Lambda$Ganck_s9Kl5o2K6eVDoQTKLc-6g.run(Unknown Source:19)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-09 19:49:31.303 E/WebViewUpdater( 1394):     at com.android.internal.util.ConcurrentUtils$1$1.run(ConcurrentUtils.java:59)
```

**Comment by ziggurad** [comment]
I have the same problem...

Xiaomi MI 5
lineage-15.1-20190101-nightly-gemini-signed.zip
open_gapps-arm64-8.1-nano-20181229.zip
[log.txt](https://github.com/opengapps/aosp_build/files/2719667/log.txt)

**Comment by 0100Light** [comment]
This is caused by an error of Android System Webview.
I solved this problem by downloading a newer version of Android System Webview apk, and change the webview in settings to the new version (should originally be "chrome version xxx").
