### ISSUE TITLE
Instructions for A/B devices

### ISSUE THREAD

**Issue by gurupras** [opengapps/aosp_build#186]
Newer devices like Google Pixel seem to be using an [A/B partition scheme](https://source.android.com/devices/tech/ota/ab/). While building for such devices, the build/flash process fails stating that the image is too large. Are there any instructions available on how to set up the AOSP build for these devices?

**Comment by Blystad** [comment]
Disable dexopt.

WITH_DEXPREOPT := false

In BoardConfig.mk
