### ISSUE TITLE
I'm build a rom for a Wifi tablet but when I exclude the packages I don't want or need it works but I still get the dialer & messaging app why is that?

### ISSUE THREAD

**Issue by BAProductions** [opengapps/aosp_build#201]
I'm build a rom for a Wifi tablet but when I exclude the packages I don't want or need it works but I still get the dialer & messaging app why is that?

`#Open Gapps PreLoaded 
GAPPS_VARIANT := super 

$(call inherit-product, vendor/opengapps/build/opengapps-packages.mk) 

#Apps I Really Want In My Custom Rom 
GAPPS_PRODUCT_PACKAGES += \ 
	FaceLock \ 
	libfilterpack_facedetect \ 
	Drive \ 
	GoogleCalendarSyncAdapter \ 
	GoogleContactsSyncAdapter \ 
	Maps \ 
	YouTube \ 
	talkback \ 
	CalculatorGoogle \ 
	GoogleBackupTransport \ 
	GoogleLoginService \ 
	GooglePartnerSetup \ 
	GoogleCamera \ 
	GoogleContacts \ 
	GooglePrintRecommendationService \ 
	GoogleServicesFramework \ 
	GoogleTTS \ 
	LatinImeGoogle \ 
	Music2 \ 
	PixelLauncherIcons \ 
	WebViewGoogle \ 
	Turbo \ 
	AndroidPlatformServices \ 
	Chrome \ 
	GoogleExtServices \ 
	GoogleFeedback \ 
	GoogleOneTimeInitializer \ 
	GooglePackageInstaller \ 
	Photos \ 
	SetupWizard \ 
	GCS \ 
	CalendarGooglePrebuilt \ 
	PrebuiltDeskClockGoogle \ 
	PrebuiltExchange3Google \ 
	PrebuiltGmail \ 
        Phonesky
	
#Open Gapps Package I Don't Want At All 
GAPPS_EXCLUDED_PACKAGES := \ 
	Books \ 
	CloudPrint2 \ 
	DMAgent \ 
	EditorsDocs \ 
	EditorsSheets \ 
	EditorsSlides \ 
	GoogleEarth \ 
	GoogleHindiIME \ 
	GoogleJapaneseInput \ 
	GooglePinyinIME \ 
	GoogleVrCore \ 
	GoogleZhuyinIME \ 
	Hangouts \ 
	KoreanIME \ 
	Newsstand \ 
	PlayGames \ 
	PlusOne \ 
	PrebuiltKeep \ 
	Street \ 
	TranslatePrebuilt \ 
	Tycho \ 
	Videos \ 
	Wallpapers \ 
	MarkupGoogle \ 
	ActionsServices \ 
	GoogleHome \ 
	GoogleExtShared \ 
	PixelLauncher \ 
	DigitalWellbeing \ 
	GoogleDialer \ 
	FitnessPrebuilt \ 
	Wallet \ 
	CarrierServices \ 
	PrebuiltBugle \ 
	TagGoogle \ 
	PrebuiltGmsCore \ 
	PrebuiltGmsCoreInstantApps \ 
	GmsCoreSetupPrebuilt 
	
#Setting 
GAPPS_PACKAGE_OVERRIDES := \ 
	FaceLock \ 
	libfilterpack_facedetect \ 
	Drive \ 
	GoogleCalendarSyncAdapter \ 
	GoogleContactsSyncAdapter \ 
	Maps \ 
	YouTube \ 
	talkback \ 
	CalculatorGoogle \ 
	GoogleBackupTransport \ 
	GoogleLoginService \ 
	GooglePartnerSetup \ 
	GoogleCamera \ 
	GoogleContacts \ 
	GooglePrintRecommendationService \ 
	GoogleServicesFramework \ 
	GoogleTTS \ 
	LatinImeGoogle \ 
	Music2 \ 
	PixelLauncherIcons \ 
	WebViewGoogle \ 
	Turbo \ 
	AndroidPlatformServices \ 
	Chrome \ 
	GoogleExtServices \ 
	GoogleFeedback \ 
	GoogleOneTimeInitializer \ 
	GooglePackageInstaller \ 
	Photos \ 
	SetupWizard \ 
	GCS \ 
	CalendarGooglePrebuilt \ 
	PrebuiltDeskClockGoogle \ 
	PrebuiltExchange3Google \ 
        PrebuiltGmail 

GAPPS_FORCE_MATCHING_DPI := true `

**Comment by jamuir** [comment]
The line `$(call inherit-product, vendor/opengapps/build/opengapps-packages.mk)` is in the wrong place.

Move it below your assignments to the gapps-package variables.

**Comment by BAProductions** [comment]
Thank I'll see if it works then close the thread.

**Comment by BAProductions** [comment]
Nothing Did Not Work At all

**Comment by jamuir** [comment]
I think you should try something simpler and verify that it has the desired effect in your build.

e.g. try adding the following lines at the bottom of your `device.mk` file:

```makefile
GAPPS_VARIANT := nano

GAPPS_PRODUCT_PACKAGES += \
    YouTube

$(call inherit-product-if-exists, vendor/opengapps/build/opengapps-packages.mk)
```

**Comment by jamuir** [comment]
@BAProductions :  can this be closed?

**Comment by BAProductions** [comment]
Yes
