### ISSUE TITLE
Unable to find an architecture compatible APK for package

### ISSUE THREAD

**Issue by truthntrick** [opengapps/aosp_build#207]
I follow the steps at README, so I download the aosp_build, all, and the arm and arm64 only the pico version. I have the following error 
vendor/opengapps/build/core/prebuilt_apk.mk:55: warning: Unable to find an architecture compatible APK for package com.google.android.gms.policy_sidecar_o defined in module AndroidPlatformServices.
vendor/opengapps/build/core/prebuilt_apk.mk:56: warning: You can try using GAPPS_EXCLUDED_PACKAGES += AndroidPlatformServices to get past this error.
vendor/opengapps/build/core/prebuilt_apk.mk:57: error: Invalid build module: AndroidPlatformServices.

**Comment by iozho** [comment]
> I follow the steps at README, so I download the aosp_build, all, and the arm and arm64 only the pico version. I have the following error
> vendor/opengapps/build/core/prebuilt_apk.mk:55: warning: Unable to find an architecture compatible APK for package com.google.android.gms.policy_sidecar_o defined in module AndroidPlatformServices.
> vendor/opengapps/build/core/prebuilt_apk.mk:56: warning: You can try using GAPPS_EXCLUDED_PACKAGES += AndroidPlatformServices to get past this error.
> vendor/opengapps/build/core/prebuilt_apk.mk:57: error: Invalid build module: AndroidPlatformServices.

I have the same issue - the problem is the new repo ( [https://gitlab.nezorfla.me/opengapps](https://gitlab.nezorfla.me/opengapps/arm64.git)). The instructions here are outdated and need to be updated. For instance all.git repo doesn't exists on github.com/opengapps/ .

**Comment by nezorflame** [comment]
Thanks for the issue, we'll update the README
cc @NicholasBuse

**Comment by nezorflame** [comment]
I think this should be closed now since @jamuir updated the README.

**Comment by GeorgBor** [comment]
Hello everyone,

does this error occured again? I get the same error just with the GoogleCamera Package.

vendor/opengapps/build/core/prebuilt_apk.mk:55: warning: Unable to find an architecture compatible APK for package com.google.GoogleCamera.gms.policy_sidecar_o defined in module GoogleCamera.
vendor/opengapps/build/core/prebuilt_apk.mk:56: warning: You can try using GAPPS_EXCLUDED_PACKAGES += GoogleCamera to get past this error.
vendor/opengapps/build/core/prebuilt_apk.mk:57: error: Invalid build module: GoogleCamera.

I'm really read the Link above carefully, but without success.

Kind Reagards
Georg
