### ISSUE TITLE
Clone speed from nezor repo is agonisingly slow

### ISSUE THREAD

**Issue by sjdrc** [opengapps/aosp_build#210]
I'm getting speeds of less than 30KiB/s from the nezor remote. I've tried on a gigabit connection and two other high speed connections with the same results. Is there anything that can be done to speed this up?

**Comment by jamuir** [comment]
the servers may just be busy.  The initial (shallow) clone does take a long time, but that should be a one-time cost.  Subsequent sync operations should be much faster.

In any case, there is nothing we can do in aosp_build to change the server clone speed.
