### ISSUE TITLE
Cannot boot when I change to nezor way using Android pie on ARM64 platform

### ISSUE THREAD

**Issue by wigcheng** [opengapps/aosp_build#211]
As title, I saw you had updated the manifest file last week, so I also update one on my source code of target device, but when I flashing the compiled images to the device, it boot failed and stocking on boot animation.

device.mk what i modify:
+$(call inherit-product, vendor/opengapps/build/opengapps-packages.mk)
+GAPPS_VARIANT := nano

It is the same configuration with previous github source, and works fine before, could you please give me some directions? thx

**Comment by jamuir** [comment]
you need to set `GAPPS_VARIANT` before you include opengapps-packages.mk.

**Comment by wigcheng** [comment]
Works, thanks a lot! my final config as following:
+# GAPPS_VARIANT := pico
 # $(call inherit-product, vendor/opengapps/build/opengapps-packages.mk)
-# GAPPS_VARIANT := nano

Another issue is happen when I boot successful:
it shows "Download Pending..." when I click the "Install" button on play store, my OS is Android Pie, and I also found the similar issue before:
https://github.com/opengapps/aosp_build/issues/184

Can I also drop out PrebuiltGmsCoreInstantApps or need to do other way?
Let me know if need create another issue post, thanks!

**Comment by jamuir** [comment]
please open another issue.
