### ISSUE TITLE
AOSP on Pixel 3 (blueline) doesn't boot (device corrupt)

### ISSUE THREAD

**Issue by CaseyBakey** [opengapps/aosp_build#214]
Hi there,

I'm currently compiling AOSP 9.0.0.r35 for my Pixel 3 (blueline).
After the build is done, when I'm trying to boot, I'm let on the bootanimation for like 2-3min, after the phone returns to the recovery mode saying that it's corrupt and proposes 2 choices : try again (to boot) or wipe the userdata and try to reboot.

Without opengapps, the build is booting normally.

Since Pixel 3 blueline is a sub-device of Pixel 3 XL. crosshatch, where should I add the needed lines?

- vendor/google/crosshatch/device.mk
or 
- vendor/google/crosshatch/blueline/BoardConfig.mk (the only *.mk file in this folder)

Is the aosp_build of opengapps still working with Pie? And does somedy tried to use to compile AOSP on Pixel 3/XL?

Thanks by advance for your answer.

**Comment by jamuir** [comment]
aosp_build is working with Pie (but I haven't tried this myself).

If you post some logs (i.e. logcat output), then we can try to help.

**Comment by CaseyBakey** [comment]
Hello there,

You're right. I was having another problem and thought it was linked with opengapps.

Everything is working fine now that the other bug is fixed.

Thanks for your answer, I close this issue.

**Comment by menshen** [comment]
> Hello there,
> 
> You're right. I was having another problem and thought it was linked with opengapps.
> 
> Everything is working fine now that the other bug is fixed.
> 
> Thanks for your answer, I close this issue.


Hello, how did you solve this problem?
**I also encountered the same problem as you.**

**Comment by CaseyBakey** [comment]
I don't think that you're having the same problem as me.

I was modding my kernel and, in the end, I forgot to concatenate the DTB files to my kernel so the device lacked hardware information to boot :o

**Comment by hmj1235** [comment]
@menshen
hi, did your problem solved?
I encountered the same issue as you.

**Comment by hmj1235** [comment]
@CaseyBakey 
Hi,
Can you tell me which *.mk file should i add those needed lines, thanks!
