### ISSUE TITLE
No APK found for package com.google.android.apps.pixelmigrate

### ISSUE THREAD

**Issue by TigerC10** [opengapps/aosp_build#215]
When building, I see this warning:

```
WARNING: No APK found compatible with API level 25 for package com.google.android.apps.pixelmigrate on all
```

I get that it's a warning, so the build should continue, but I'm wondering if this will cause some instability in the google play services.

**Comment by jamuir** [comment]
Are you building in a Nougat tree? (api level 25)

if you look at the file `opengapps-packages.mk`, then you can see that that apk should only be added when building for Oreo or newer.

see the following commit:  7021e5d5dc4c68b155be1d43b8c5e21103de2cb5
