### ISSUE TITLE
Compile on Mac OS 10.14

### ISSUE THREAD

**Issue by FeeJai** [opengapps/aosp_build#216]
`[1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
device/google/taimen/device.mk was modified, regenerating...
sandbox-exec: sandbox_apply_container: Operation not permitted
12:21:06 dumpvars failed with: exit status 71
device/google/taimen/device.mk was modified, regenerating...
sandbox-exec: sandbox_apply_container: Operation not permitted
12:21:33 dumpvars failed with: exit status 71`

and then finally:
`build/make/core/tasks/vendor_module_check.mk:82: error: Error: Product "aosp_taimen" cannot have overlay in vendor tree: vendor/opengapps/build/overlay/pico vendor/opengapps/build/overlay/assistant/28.`

Seems to be a problem of 10.14 Mojave

**Comment by jamuir** [comment]
> `Error: Product "aosp_taimen" cannot have overlay in vendor tree`

This is a known issue that has been reported previously.  It is not mac specific.

You can work around it like this:

```diff
diff --git a/aosp_taimen.mk b/aosp_taimen.mk
index 5653fd5..a3ac694 100644
--- a/aosp_taimen.mk
+++ b/aosp_taimen.mk
@@ -33,7 +33,7 @@ PRODUCT_COPY_FILES += \
     device/google/taimen/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
     frameworks/native/data/etc/aosp_excluded_hardware.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/aosp_excluded_hardware.xml
 
-PRODUCT_RESTRICT_VENDOR_FILES := owner
+PRODUCT_RESTRICT_VENDOR_FILES := false
 
 PRODUCT_MANUFACTURER := Google
 PRODUCT_BRAND := Android
```
