### ISSUE TITLE
Can't open system when build with opengapps

### ISSUE THREAD

**Issue by menshen** [opengapps/aosp_build#219]
Device: Nexus 6P
Android System: 8.1.0
I download the opengapps source to my android source , and i recompile android source .
but when i flash the new system to my device , the device can't open .
the screen disply :
can't load android system. Your data my be corrut. If you continue to get this messsage, you may need to perform a factory data reset and erase all user data stored on this device .
how can i do ?
help me , thanks .
best regards

**Comment by jamuir** [comment]
this doesn't sound related to opengapps.

To wipe your data partition, you can boot into fastboot mode and then run `fastboot -w reboot`
