### ISSUE TITLE
Running into an overlay issue with 6.0.1

### ISSUE THREAD

**Issue by Fuzion24** [opengapps/aosp_build#22]
build/core/tasks/vendor_module_check.mk:58: *** Error: Product "aosp_hammerhead" cannot have overlay in vendor tree: vendor/google/build/overlay/stock.  Stop.

**Comment by Blystad** [comment]
You need to comment out:

```
PRODUCT_RESTRICT_VENDOR_FILES 
```

See: https://android.googlesource.com/device/lge/hammerhead/+/master/full_hammerhead.mk#31
