### ISSUE TITLE
Unable to clone/sync gitlab files

### ISSUE THREAD

**Issue by AlbertBackenhof** [opengapps/aosp_build#223]
Fetching the source from gitlab with:
<remote name="gitlab" fetch="https://gitlab.opengapps.org/opengapps/"  />
fails with error: 500.

Same error when trying to clone the gits with git clone.
git clone https://gitlab.opengapps.org/opengapps/arm64.git/

fatal: unable to access 'https://gitlab.opengapps.org/opengapps/arm64.git/': The requested URL returned error: 500

Is the gitlab repo down? I have tried the gitlab.nezorfla.me as well but with the same result.

**Comment by alviteri** [comment]
Temporary down ... It was down yesterday too ... Then comes up and down again ... Maintenance probably ... We can wait

**Comment by AlbertBackenhof** [comment]
Ok, thanks for the quick reply!
