### ISSUE TITLE
Support for Android10 AOSP

### ISSUE THREAD

**Issue by suwish0** [opengapps/aosp_build#224]
Google has released [android-10.0.0_r2 and android-10.0.0_r1](https://source.android.com/setup/start/build-numbers#source-code-tags-and-builds) AOSP repo tag. Wonder when is expected to update this project to support Android10? Can't wait to flash my Pixel.

**Comment by alviteri** [comment]
Pay for ask ETA .... Otherwise wait a bit ... Patience and don't open anymore an issue like this
