### ISSUE TITLE
Device is not play protect certified

### ISSUE THREAD

**Issue by tranchikha** [opengapps/aosp_build#232]
Hello developer,

I try to add GApps into my AOSP build and flash my images. I could see all Google apps. However, I tried to open Play store and got issue "Device is not play protect certified".

Does anyone face same issue?
Please give me your suggestion/solution if any.

I would be graceful.

Thank you so much

Regards,
Kha Tran

**Comment by ArnauBG** [comment]
You have to verify your ROM on Android's website: [https://www.google.com/android/uncertified/](url)

**Comment by tranchikha** [comment]
Hi @ArnauBG ,

Thank you very much (y)!

I understood what’s mising?

Regards, Kha

**Comment by ArnauBG** [comment]
Yes, you understood @tranchikha

Entering [Android's Custom ROMS](https://www.google.com/android/uncertified/) website, logging in and entering the ID, will enable the Play Store and much more apps.
Is possible that you need to wait a few after registering your ROM.

Hope it worked for you.

**Comment by tranchikha** [comment]
Hi @ArnauBG,

I could make Gapps work on my device with your instruction. Thank you very much for your support.

So I close this issue.

**Comment by amlan007** [comment]
What if we want ro run GAPPS without registering GSF ID on google portal ?

Is there anyway to bypass that ?

**Comment by yogeshsh** [comment]
@amlan007 have you got any solution on this ?
