### ISSUE TITLE
FaceLock failure when trying to build gitlab ten branch

### ISSUE THREAD

**Issue by stefanhh0** [opengapps/aosp_build#238]
When trying to build the opengapps gitlab branch ten, I run into following:

[ 88% 574/651] including vendor/opengapps/build/modules/FaceLock/Android.mk ...
FAILED: 
vendor/nxp/Android.mk: error: FaceLock: No source files specified 
build/make/core/prebuilt_internal.mk:37: error: done.
01:38:39 ckati failed with: exit status 1

My workaround for now seems to be:
rm -r vendor/opengapps/build/modules/FaceLock

**Comment by MarijnS95** [comment]
FaceLock is not supported on 29 anymore, and has been removed:
https://gitlab.opengapps.org/opengapps/arm64/merge_requests/1/diffs?commit_id=51b28ddaca5baaa531dbd70a82a50535e9f863f0

You can use something like this. If it works for you too I'll go ahead and PR it:
https://github.com/MarijnS95/opengapps_aosp_build/commit/8f9b3aa0489d032f0c91f6e2680d7f15b7ac2348

**Comment by stefanhh0** [comment]
Your change works just fine. I have reverted the rm command in my script. Thanks for it.
