### ISSUE TITLE
Android 9 build contains opengapps-permissions-q.xml and opengapps-permissions.xml

### ISSUE THREAD

**Issue by nexus511** [opengapps/aosp_build#249]
If integrated into an AOSP build, both files are currently added to the system.

As there are entries that make Android 9 systems bootloop in the opengapps-permissions-q.xml, this should not be added to the system for API-levels before 29.

I guess that this is the same for Android 10 as well, as there is no distinction and the file is added in opengapps-files.mk by `gapps_etc_files := $(call gapps-copy-to-system,all,etc)`.

I removed the file manually from my device. This allowed booting into the android system properly. I will work on a patch to remove it from the build.

**Comment by MarijnS95** [comment]
See https://github.com/opengapps/aosp_build/pull/247/

**Comment by nexus511** [comment]
@MarijnS95 That looks exactly like my patch. Than I close this ticket and hope, that it gets merged at some point.

**Comment by MarijnS95** [comment]
@nexus511 You might leave this issue open for others to find and as a nudge to collaborators to take a look at it :wink:

**Comment by nexus511** [comment]
@MarijnS95 Good point. As it has now been merged already, I guess it is still fine to have it closed.

**Comment by nezorflame** [comment]
Thanks for merging! I'm out of town for this weekend so I don't have the capability to properly review.
