### ISSUE TITLE
Problemens with AndroidMigratePrebuilt

### ISSUE THREAD

**Issue by mamutal91** [opengapps/aosp_build#250]
I'm having trouble trying to compile with aosp_build.

He gave me the indication to add the line

GAPPS_EXCLUDED_PACKAGES += AndroidMigratePrebuilt

However, the problem remains

> [vendor/opengapps/sources/arm64/priv-app/com.google.android.as/29/nodpi/793748.apk]
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> note:  vendor/opengapps/sources/arm64/priv-app/com.google.android.as/29/nodpi/793748.apk may be a plain executable, not an archive
> zipinfo:  cannot find zipfile directory in one of vendor/opengapps/sources/arm64/priv-app/com.google.android.as/29/nodpi/793748.apk or
>           vendor/opengapps/sources/arm64/priv-app/com.google.android.as/29/nodpi/793748.apk.zip, and cannot find vendor/opengapps/sources/arm64/priv-app/com.google.android.as/29/nodpi/793748.apk.ZIP, period.
> [ 84% 455/540] including vendor/opengapps/build/modules/AndroidMigratePrebuilt/Android.mk ...
> FAILED:
> zipinfo:  cannot find or open , .zip or .ZIP.
> vendor/nxp/opensource/sn100x/Android.mk: error: AndroidMigratePrebuilt: No source files specified
> build/make/core/prebuilt_internal.mk:37: error: done.

**Comment by MartinX3** [comment]
Try
https://github.com/opengapps/aosp_build/issues/229

**Comment by mamutal91** [comment]
I still have the same problem

> FAILED: out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk
> /bin/bash -c "(rm -f out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk ) && (cp \"vendor/opengapps/sources/all/app/com.google.android.syncadapters.calendar/21/nodpi/2016184095.apk\" \"out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk\" ) && (if (zipinfo out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then out/soong/host/linux-x86/bin/zip2zip -i out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk -o out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.tmp -0 'lib/**/*.so'  && mv -f out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.tmp out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk ; fi ) && (if ! out/host/linux-x86/bin/zipalign -c  4 out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk >/dev/null ; then mv out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned; out/host/linux-x86/bin/zipalign -f -p 4 out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned; mv out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk; fi )"
> Unable to open 'out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk' for verification
> Unable to open 'out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned' as zip archive
> mv: bad 'out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned': No such file or directory
> FAILED: out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk
> /bin/bash -c "(rm -f out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk ) && (cp \"vendor/opengapps/sources/all/app/com.google.android.syncadapters.calendar/21/nodpi/2016184095.apk\" \"out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk\" ) && (if (zipinfo out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then out/soong/host/linux-x86/bin/zip2zip -i out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk -o out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.tmp -0 'lib/**/*.so'  && mv -f out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.tmp out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk ; fi ) && (if ! out/host/linux-x86/bin/zipalign -c  4 out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk >/dev/null ; then mv out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned; out/host/linux-x86/bin/zipalign -f -p 4 out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned; mv out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk; fi )"
> Unable to open 'out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk' for verification
> Unable to open 'out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned' as zip archive
> mv: bad 'out/target/product/beryllium/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned': No such file or directory
>

**Comment by MartinX3** [comment]
Weird, it sounds for me that you didn't update the lfs after the last git pull

**Comment by mamutal91** [comment]
I made it
  cd $HOME/aosp/vendor/opengapps/build && git lfs fetch --all
  cd $HOME/aosp/vendor/opengapps/sources/all && git lfs fetch --all
  cd $HOME/aosp/vendor/opengapps/sources/arm && git lfs fetch --all
  cd $HOME/aosp/vendor/opengapps/sources/arm64 && git lfs fetch --all
  cd $HOME/aosp/vendor/opengapps/sources/x86 && git lfs fetch --all
  cd $HOME/aosp/aosp/vendor/opengapps/sources/x86_64 && git lfs fetch --all

> Weird, it sounds for me that you didn't update the lfs after the last git pull

**Comment by stefanhh0** [comment]
@mamutal91 If it is fixed for you please also close this issue.
