### ISSUE TITLE
Check for PRODUCT_AAPT_* value in device.mk required

### ISSUE THREAD

**Issue by fonic** [opengapps/aosp_build#29]
I think opengapps should check if `PRODUCT_AAPT_*` values are present/set in device.mk.

I integrated opengapps in my AOSP build for the HiKey reference board (device/linaro/hikey) and encountered strange build errors because the device.mk for that device lacks those values. If they are missing, `vendor/google/build/core/find_apk.sh` receives wrong arguments and fails to locate packages.

**Comment by Blystad** [comment]
Please check if #31 fixed it for you.

**Comment by Blystad** [comment]
Seeing as I haven't heard anything on this for a while, I'm going to assume that #31 fixed it, and close this.
