### ISSUE TITLE
Prebuilt & Run GAPPS on AOSP without registering GSF ID

### ISSUE THREAD

**Issue by amlan007** [opengapps/aosp_build#302]
What if we want ro run GAPPS without registering GSF ID on google portal ?

Is there anyway to bypass that ?

**Comment by acr92** [comment]
If you are using a device that doesn't have any Google certification, then no.

Google whitelists devices in their system based on the fingerprint, the device brand and model. If it cannot find the device, then it'll show the "Unlicensed" error.

**Comment by amlan007** [comment]
Hi Arne

Is there any way to run all google apps without registering GSF Identifier ?

Thanks
Amlan

**Comment by acr92** [comment]
What is your device info & ro.build.fingerprint?

**Comment by amlan007** [comment]
Hi Arne,

We are building an android based laptop which is based on AOSP.
We want to release that product into the market with GAPPS.

*Product Name* : JioBook based on Android 11
* ro.build.fingerprint*:
Jio/JioBook/JioBook:11/D.001.01.00.21/JioBook_NB1112MM_001.01.00.21.D_050223:user/release-keys

Thanks
Amlan

**Comment by acr92** [comment]
Hey Amlan,

You would need to go through the proper certification process if you're
launching a new product. OpenGapps is for already certified products, for
custom ROM developers.

When you go through the certification process you'll get whitelisted, and
receive a zip file of all the Google applications and their official build
scripts.

You'll have a problem though, as the certification window for new devices
with Android 11 expired a year ago (and A11 is end of life February 2024).
Google only allows certification of new Android 13 based devices now.

To go through the certification process you need to use a Google Partner
ODM ( https://www.android.com/certified/partners/#tab-panel-odms ).

Hope this helps.

**Comment by amlan007** [comment]
Hi Arne

Any other way to run all google applications without certification ?

How about MicroG or any other better alternative ?

Thanks
Amlan

**Comment by acr92** [comment]
I'm not aware of any possibilities, and in any case it's illegal to use GMS
without the proper certification, and signed agreements with Google.
