### ISSUE TITLE
Build errors if ${ANDROID_BUILD_TOP} contains spaces

### ISSUE THREAD

**Issue by fonic** [opengapps/aosp_build#32]
At first I put my Android sources in a path containing spaces (`Android AOSP`). This results in build errors. I'm not entirely sure if this is a problem with OpenGApps or the AOSP build system itself.

Either this is fixed or the README is updated with a note regarding this.

**Comment by Dudulle** [comment]
If I remember correctly, aosp doesn't support spaces in paths.
If it did, this project should also work with spaces.
Every path in makefile are relative (or maybe i missed something?). The only paths which could contain spaces are inside the bash file which should handle it.

**Comment by fonic** [comment]
You might be right, I didn't investigate this further. I would suggest putting this in the 'Caveats' section of the README.

**Comment by Blystad** [comment]
Can you provide a build log (just `make droid | tee build.log` or similar)?

**Comment by fonic** [comment]
No need to - I checked it again, it's not related to OpenGApps. It's the AOSP build system itself,  Dudulle was right. Sorry, my fault.
