### ISSUE TITLE
Path to prebuilt `aapt` is different on 5.1.1 vs 6.0.1

### ISSUE THREAD

**Issue by aaboyd** [opengapps/aosp_build#34]
On line [13 of Config.mk](https://github.com/opengapps/aosp_build/blob/master/config.mk#L13) the path to AAPT doesn't contain to `bin` on the `android-5.1.1_r36` but on the `android-6.0.1_r21` branch it does.

References
https://android.googlesource.com/platform/prebuilts/sdk/+/android-6.0.1_r21/tools/linux
https://android.googlesource.com/platform/prebuilts/sdk/+/android-5.1.1_r36/tools/linux/

**Comment by Blystad** [comment]
It's not supposed to be easy...is it...

I suggest replacing it with:

```
GAPPS_AAPT_PATH := $(shell find prebuilts/sdk/tools/$(HOST_OS) -executable -name aapt | head -n1)
```

I think that should do the trick. But please test, and feel free to submit a PR. It would be appreciated :)

**Comment by mfonville** [comment]
@Blystad some shells do difficult with/without space in the `head` command arguments, be sure to use `head -n 1` to stay Posix and avoid trouble
