### ISSUE TITLE
com.google.android.gm.exchange package is missing

### ISSUE THREAD

**Issue by discipuloosho** [opengapps/aosp_build#43]

**Comment by mfonville** [comment]
@Blystad I did remove this package yesterday, because the functionality is now integrated in the GMail app and the google exchange service has been removed from the latest Nexus image.

**Comment by discipuloosho** [comment]
Ok, so you could remove modules/PrebuiltExchage3Google to avoid confusion. Thanks

**Comment by mfonville** [comment]
Let's keep the issue open until @Blystad finds the time to apply the fix. (I am not the aosp_build maintainer)

**Comment by Blystad** [comment]
Removed in commit: b90e42365fc7a39b3e8026bb8355a5e6ebe9a2f1

**Comment by mfonville** [comment]
I had made a mistake, and instead of completely removing ExchangeGoogle it has moved from /app to /priv-app
So we need to revert that last commit, and update the install path.
