### ISSUE TITLE
Android device manager doesn't work

### ISSUE THREAD

**Issue by discipuloosho** [opengapps/aosp_build#59]
Hello guys. Device Manager feature doesn't work for me with GAPPS_VARIANT := micro in CM13. My motorola nexus 6 doesn't appear in google play device manager page. But all options are properly activated. Thanks.

**Comment by Blystad** [comment]
You probably need the Setup Wizard as well. I think that's responsible for activating the device manager.

Also, check in your Settings > Security > Device Manager and check if it's enabled.

**Comment by discipuloosho** [comment]
Setup Wizar is installed and properly configured. And Settings > Security > Device Manager properly activated. :S

**Comment by Blystad** [comment]
Strange....try turning it off and on again in the Device Manager setting. Also try opening Google Play store and update all apps, and see if that helps.

**Comment by discipuloosho** [comment]
I look at it

**Comment by discipuloosho** [comment]
Ok. The problem is the following: CyanogenSetupWizard conflict with GoogleSetupWizard, CyanogenSetupWizard doesn't allow GoogleSetupWizard end properly (due this device manager doesn't work). But, CyanogenSetupWizard can not be removed because notification panel doesn't work. It is a dead end.
