### ISSUE TITLE
Build problem with Nexus 5X (possibly Nexus 6P too) due to new vendor partition

### ISSUE THREAD

**Issue by CaseyBakey** [opengapps/aosp_build#63]
Hello there,

I did follow the instructions on the readme to integrate opengapps into my AOSP build but I'm encountering problems:

`Target system fs image: out/target/product/bullhead/obj/PACKAGING/systemimage_intermediates/system.img
Non-symlink out/target/product/bullhead/system/vendor detected!
You cannot install files to out/target/product/bullhead/system/vendor while building a separate vendor.img!
make: *** [out/target/product/bullhead/obj/PACKAGING/systemimage_intermediates/system.img] Error 1
make: *** Waiting for unfinished jobs....
`

I guess it has to do with the new partition layout of N5X/N6P:

http://forum.xda-developers.com/nexus-6p/general/developer-discussion-flashing-vendor-t3246767

I did try to edit every scripts from this repo mentioning /system/vendor, to point to /vendor instead, but it wasn't enough.

I'm not a git guru nor an Android one (first AOSP build attempt here), so I'll be glad to receive some help here ;)

Thanks again for your work!

**Comment by mfonville** [comment]
@Blystad for devices that have their own `/vendor` partition we should probably not touch it (and users should not flash it, only flashing their `/system`)

**Comment by CaseyBakey** [comment]
So what should I do exactly?

**Comment by Blystad** [comment]
Try to delete `vendor/pittpatt `in `opengapps-files.mk` and see if it works then.

If it does we just need to find which board variables is set, and exclude this folder in cases where the device has a vendor partition

**Comment by CaseyBakey** [comment]
Ok, I have first to finish a build and then I'll try.
But deleting pittpatt will break facial recognition, right? I'm not using it but just to know.

**Comment by Blystad** [comment]
Your vendor.img will probably already contain them. So as long as you don't
flash that, you should be OK.

**Comment by CaseyBakey** [comment]
Ok, perfect. Thanks for your fast answser, I'll keep you updated!

**Comment by mfonville** [comment]
@Blystad @CaseyBakey I can indeed (from the regular Open GApps packages) confirm that if you have flashed your `/vendor` from the regular stock images (and you should update it sometimes) the files should already be there.

Having `/vendor` separate is imho btw a good new practice set by Google that should probably become the default for other devices too.

**Comment by Blystad** [comment]
Yep. Did some tracking and seems that if `TARGET_COPY_OUT_VENDOR` is set to `vendor` then it's a separate `vendor.img`.

If that works @CaseyBakey then I would like you to check out the `vendor_pittpatt_error` branch (see PR #65) and tell me if that works. It should, but it's a bit difficult to verify 100% :)

**Comment by CaseyBakey** [comment]
Removing 

> vendor/pittpatt in opengapps-files.mk

seemed to do the trick.

I did however encounter an overlay issue, fixed like you said here:
https://github.com/opengapps/aosp_build/issues/22

Btw, since I wasn't sure the .mk file would do the trick, I did go to vendor/opengapps, and use manually the download_source script and the make, before attempting to build the full ROM.

Build and signing finished! Flashing ongoing.

**Comment by Blystad** [comment]
Ok, great, can you verify that my branch works as well? Then I'll get that merged and hopefully no one else will encounter a similar issue :)

**Comment by CaseyBakey** [comment]
Hello back,

I'm not sure how the AOSP build system is working so I did:
`cd vendor/google/build
git fetch
git checkout origin/vendor_pittpatt_error
cd ../../../
make -j4`

I'm not sure if it's sufficient. I would like to avoid cleaning and building from scratch the whole stuff ^^

However, I did get this:

> Copy: out/target/product/bullhead/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin
mkdir: cannot create directory 'out/target/product/bullhead/system/vendor': File exists
make: *** [out/target/product/bullhead/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.8/landmark_group_meta_data.bin] Error 1
make: *** Waiting for unfinished jobs....
warning: string 'gsm_alphabet_default_charset' has no default translation.

> #### make failed to build some targets (03:09 (mm:ss)) ####

I guess I'm good to clean and retry? :/
Or is there another clever trick?

**Comment by Blystad** [comment]
Blergh, seems it didn't work then. I'll look into it.

**Comment by Blystad** [comment]
This isn't an issue on Nougat (since vendor/pittpatt apparently has disappeared). So I'll close this. For L and M, just delete or comment out the line copying vendor/pittpatt (see PR #76)

**Comment by CaseyBakey** [comment]
Hello there!

I'm not building AOSP N (CopperheadOS) and I can confirm I still encounter the same issue.

The same fix also still works.

Regards

**Comment by NateDev100** [comment]
I'm trying this and I get this error too, even after commenting out Pitpatt vendor stuff.

**Comment by Blystad** [comment]
@NateDev100 are you sure you're getting the same error, or could it be that you're getting the error in #146 ?

**Comment by NateDev100** [comment]
Whoops commented on the wrong issue, sorry :(
