### ISSUE TITLE
libfilterpack_facedetect.so, libfrsdk.so does not exist

### ISSUE THREAD

**Issue by utkuacer** [opengapps/aosp_build#71]
Hi,

I am following your instructions to include open gapps to my aosp build but when I try to make I receive the following errors. Any suggestions? 

Thanks a lot

target Unpacked: libfilterpack_facedetect (out/target/product/bullhead/obj/SHARED_LIBRARIES/libfilterpack_facedetect_intermediates/PACKED/libfilterpack_facedetect.so)
target Unpacked: libfacelock_jni (out/target/product/bullhead/obj/SHARED_LIBRARIES/libfacelock_jni_intermediates/PACKED/libfacelock_jni.so)
target Unpacked: libfrsdk (out/target/product/bullhead/obj/SHARED_LIBRARIES/libfrsdk_intermediates/PACKED/libfrsdk.so)
acp: file 'out/target/product/bullhead/obj/SHARED_LIBRARIES/libfacelock_jni_intermediates/LINKED/libfacelock_jni.so' does not exist
make: *** [out/target/product/bullhead/obj/SHARED_LIBRARIES/libfacelock_jni_intermediates/PACKED/libfacelock_jni.so] Error 1
make: *** Waiting for unfinished jobs....
acp: file 'out/target/product/bullhead/obj/SHARED_LIBRARIES/libfilterpack_facedetect_intermediates/LINKED/libfilterpack_facedetect.so' does not exist
make: *** [out/target/product/bullhead/obj/SHARED_LIBRARIES/libfilterpack_facedetect_intermediates/PACKED/libfilterpack_facedetect.so] Error 1
acp: file 'out/target/product/bullhead/obj/SHARED_LIBRARIES/libfrsdk_intermediates/LINKED/libfrsdk.so' does not exist
make: *** [out/target/product/bullhead/obj/SHARED_LIBRARIES/libfrsdk_intermediates/PACKED/libfrsdk.so] Error 1

**Comment by Blystad** [comment]
Hey, I'm away on vacation this week. I'll get back with a more complete
answer once I'm back. Meanwhile, check that you have the expected
vendor/opengapps/ folders for your architecture.

Regards
Arne Christian

**Comment by utkuacer** [comment]
Thanks a lot for your response

Changing 'arm' to 'arm64' in the additions to manifest.xml after realizing bullhead needed arm64 architecture instead of arm solved it. But now, I am having another problem with Chrome.  

unzip:  cannot find or open out/target/product/bullhead/obj/APPS/Chrome_intermediates/package.apk, out/target/product/bullhead/obj/APPS/Chrome_intermediates/package.apk.zip or out/target/product/bullhead/obj/APPS/Chrome_intermediates/package.apk.ZIP.
mv: cannot stat 'out/target/product/bullhead/obj/APPS/Chrome_intermediates/package.apk': No such file or directory
make: *** [out/target/product/bullhead/obj/APPS/Chrome_intermediates/package.apk] Error 1

**Comment by Dudulle** [comment]
Not all packages have a 64bit variant.
For the arm64 target, you must include both arm and arm64 sources (and the "all" sources but I suppose you already have it).

**Comment by utkuacer** [comment]
Yes, I figured it. I have no problem now. Thanks a lot
