### ISSUE TITLE
CalculatorGoogle is now API21

### ISSUE THREAD

**Issue by mfonville** [opengapps/aosp_build#72]
Hey,

CalculatorGoogle used to be API23+ but their newest versions are API21+
It has been tested to work well on Android 5.x devices, and the regular opengapps scripts are already updated now to put the calculator for the 5.x packages too.
It would be nice to also update aosp_build and add CalculatorGoogle to the API21+ builds.

**Comment by Blystad** [comment]
Fixed in PR #76
