### ISSUE TITLE
Add support for lz compressed files

### ISSUE THREAD

**Issue by Blystad** [opengapps/aosp_build#79]
Ref [opengapps/opengapps#6291b4e36a9f](https://github.com/opengapps/arm64/commit/6291b4e36a9fd9f8ee31d1628ca872b02b1da2f4) the new Chrome APK is above the Github file size limit (100MB), so it's lz compressed.

**Comment by mikey0000** [comment]
what about using github LFS??

**Comment by Blystad** [comment]
Github LFS is too expensive. You get 1GB of bandwidth a month. And they charge 5$ for every 50GB consumed thereafter. That'll end up with a lot of money every month :) :(

**Comment by jamuir** [comment]
Missing support for lz compression causes the wrong Chrome apk to be installed on bullhead, which lead me to open the following issue: https://github.com/opengapps/aosp_build/issues/89

If you manually decompress the Chrome apk.lz file in your tree, then everything works fine.

**Comment by jamuir** [comment]
@Blystad:  I've added support for lz compressed files in the following PR:  https://github.com/opengapps/aosp_build/pull/90

**Comment by Blystad** [comment]
Fixed with PR #90
