### ISSUE TITLE
Possible missing parts from GApps N

### ISSUE THREAD

**Issue by AdFad666** [opengapps/aosp_build#82]
```
09-12 23:17:37.782: E/Icing(3577): dlopen failed: library "/data/data/com.google.android.gms/files/libAppDataSearchExt_arm64_v8a.so" not found
09-12 23:17:37.782: E/Icing(3577): Loading extension /data/data/com.google.android.gms/files/libAppDataSearchExt_arm64_v8a.so failed
```

That sounds like something which should come from GApps?

**Comment by AdFad666** [comment]
To be clear I'm building GApps into my ROM, not flashing, in case you thought my poorly worded issue was a report for the zip.

**Comment by Blystad** [comment]
That you're building GApps into the ROM is implicit here :) But alright, searching for the above file, I find multiple logcats and posts with the same lines, all the way back to October 2015. So don't think it's a new issue in N. I don't know if it's any dangerous that the file is missing.

**Comment by AdFad666** [comment]
Not dangerous, but Our Googley Overlord is not happy none-the-less. judging by `libAppDataSearchExt` I'll try to see if app data search is actually working. (I'm not sure if I've ever used that feature so I'll need to investigate what I should be looking for.)

**Comment by mfonville** [comment]
The files don't exist on stock ROMs and they have a different name inside the GMS ``libAppDataSearch.so``

isn't it maybe a leftover that they forgot from the 4.4 era (where libs were not split per architecture folder)?

**Comment by Blystad** [comment]
Probably from 4.4 era. Do these errors pop up on Lollipop/Marshmallow?

**Comment by mfonville** [comment]
They pop up on any known version. If you Google for them on the internet, they are everywhere, but they are non-fatal. GMS just checks if they exist...

**Comment by Blystad** [comment]
Closing this issue then.
