### ISSUE TITLE
"Cannot have overlay in vendor tree"

### ISSUE THREAD

**Issue by BrianAllred** [opengapps/aosp_build#85]
Building the latest CopperheadOS with OpenGapps stock variant for the Nexus 6P results in the following error:

`build/core/tasks/vendor_module_check.mk:58: *** Error: Product "aosp_angler" cannot have overlay in vendor tree: vendor/google/build/overlay/pico vendor/google/build/overlay/webview/24 vendor/google/build/overlay/browser vendor/google/build/overlay/dialer vendor/google/build/overlay/mms.
make: *** [build/core/ninja.mk:164: out/build-aosp_angler-dist.ninja] Error 1`

**Comment by Blystad** [comment]
See #63
