### ISSUE TITLE
Cleanup unnecessary extracted .lz files

### ISSUE THREAD

**Issue by Blystad** [opengapps/aosp_build#91]
We now extract .lz files and keep them for old APKs. We'll properly select the new APK, but we should delete the old APKs, otherwise the vendor/opengapps/sources dirs will grow for each new updated version.

See PR #90 for a discussion on this topic.

**Comment by jamuir** [comment]
a clean-up operation is implemented in PR https://github.com/opengapps/aosp_build/pull/97.
